# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('type_of_land', models.CharField(max_length=50)),
                ('type_of_path', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=50)),
                ('high_tension', models.CharField(max_length=50)),
                ('river', models.CharField(max_length=50)),
                ('shape', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('road_width', models.FloatField()),
                ('gov_rate', models.FloatField()),
                ('com_rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Housing'),
        ),
    ]
